name: power_state
description: A flutter state management solution with dependency injection. You can easily manage your state
version: 0.0.3
homepage: https://github.com/sanjidbillah/power_state
repository: https://github.com/sanjidbillah/power_state

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

