#The name of your workflow.
name: build
# Trigger the workflow on push or pull request
on:
  push:
    branches: [main,dev]
  pull_request:
    branches: [main,dev]
#A workflow run is made up of one or more jobs. Jobs run in parallel by default.
jobs:
  test:
    #The type of machine to run the job on. [windows,macos, ubuntu , self-hosted]
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
    #sequence of tasks called
    steps:
      # The branch or tag ref that triggered the workflow will be checked out.
      # https://github.com/actions/checkout
      - uses: actions/checkout@v3
      # Setup a flutter environment.
      # https://github.com/marketplace/actions/flutter-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.2"
          channel: "stable"
      - run: flutter pub get
      #- run: flutter analyze
      # run  flutter widgets tests  and unit tests
      - run: flutter test --coverage
      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: coverage/lcov.info
          min_coverage: 90

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
